name: localtileserver-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - click
  - flask>=2.0.0
  - Flask-Caching
  - GDAL
  - requests
  - scooby
  - furl
  - shapely
  - localtileserver>=0.3.8
  - pip
  - leafmap
  - geemap
  - rio-cogeo
