name: geo-env
channels:
  - conda-forge
dependencies:
  - datapane
  - flask>=2.0.0
  - flask-caching
  - gdal
  - geemap
  - geopandas
  - imageio
  - keplergl
  - leafmap
  - localtileserver>=0.3.8
  - pip
  - pydeck
  - python>=3.8
  - requests
  - rio-cogeo
  - tifffile
