name: geo-env
channels:
  - conda-forge
dependencies:
  - datapane
  - flask>=2.0.0
  - flask-caching
  - gdal
  - geemap>=0.11.0
  - geopandas
  - imageio
  - keplergl
  - leafmap>=0.7.2
  - localtileserver>=0.4.0
  - pip
  - pydeck
  - python>=3.8
  - requests
  - rio-cogeo
  - tifffile
